server:
  port: 32000

spring:
  application:
    name: app-service

  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20000/eureka/